version: '3.8'

services:
  web:
    build:
      context: .
    volumes:
      - .:/pricep
    ports:
      - "${PORT}:${PORT}"  
    environment:
      - PORT=8080 
    command: /bin/bash -c "playwright install --with-deps && python manage.py runserver 0.0.0.0:${PORT}"
