services:
  - name: pricep-web
    type: web
    env: docker
    region: oregon  
    plan: free  
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "yourdomain.com,render.com,localhost,127.0.0.1"
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        value: "postgres://user:password@host:port/dbname"
